site_name: Finance

repo_name: Finance
repo_url: 'https://github.com/fellipe-araujo/Finance'

copyright: 'Copyright &copy; 2020 Finance'

theme:
  name: 'material'
  palette:
    - scheme: 'slate'
      primary: 'purple'
      accent: 'purple'
nav:
  - Início: index.md
  - Banco de Dados:
    - ME-R: Database/mer.md
  - Políticas:
    - Branches: Policies/branch.md
    - Commits: Policies/commit.md
    - Issues: Policies/issue.md
    - PRs: Policies/pr.md